### ISSUE TITLE
Training and evaluating on 'mix_clean'

### ISSUE THREAD

**Issue by lienz** [sp-uhh/dual-path-rnn#1]
Hi,
Thanks for sharing your implementation of DualPathRNN. The README file mentions 14.5 on the test set of WHAM! I first assumed it was in the noisy conditions, however your code seems to train and evaluate using "mix_clean" mixtures (equivalent to the standard wsj0-2mix dataset), while the noisy mixtures are in the folder "mix_both". Is it correct that your model gets 14.5 SI-SNR improvement in clean conditions, and not noisy? Thank you in advance for your answer.
https://github.com/sp-uhh/dual-path-rnn/blob/46427f7efac17dfb4a96b7a70063fa5db51583ce/src/data.py#L23

**Comment by dditter** [comment]
Hi,
you are correct, for the experiments and their evaluation I refer only the "mix_clean" subset of the WHAM! data set which is equal to the WSJ0-MIX2 data set, i.e. clean conditions. Sorry about the confusing formulation in the README.md, I will reformulate this passage to make this point clearer.
